/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.md",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#f8fafc',
        'text-primary': '#1e293b',
        'text-secondary': '#475569',
        'card-background': '#ffffff',
        'border': '#e2e8f0',
        'accent-blue': '#3b82f6',
        'accent-purple': '#9333ea',
        'dark-background': '#1e293b',
        'dark-text-primary': '#f8fafc',
        'dark-text-secondary': '#94a3b8',
        'dark-card-background': '#334155',
        'dark-border': '#475569',
        'dark-accent-blue': '#60a5fa',
        'dark-accent-purple': '#c084fc',
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
  safelist: [
    'bg-background',
    'text-primary',
    'text-secondary',
    'bg-card-background',
    'border-border',
    'bg-accent-blue',
    'text-accent-blue',
    'bg-accent-purple',
    'text-accent-purple',
    'bg-dark-background',
    'dark-text-primary',
    'text-dark-secondary',
    'bg-dark-card-background',
    'border-dark-border',
    'bg-dark-accent-blue',
    'text-dark-accent-blue',
    'bg-dark-accent-purple',
    'text-dark-accent-purple',
  ],
}