name: Deploy Potemkin Page to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to gh-pages branch
      pages: write # Required to deploy to GitHub Pages
      id-token: write # Required for OpenID Connect (OIDC) authentication

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # Use the latest Python 3 version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install markdown

    - name: Generate HTML page
      run: python gerar_pagina.py

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.' # Uploads the entire current directory (which contains index.html)

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4