name: Deploy Potemkin Page to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Use Node.js 20

    - name: Install Node.js dependencies
      run: npm install
      working-directory: ./frontend

    - name: Build React application
      run: npm run build
      working-directory: ./frontend

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './frontend/dist'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4